[package]
name = "google-draco"
version = "0.1.0"
authors = ["Benjamin Wasty <benny.wasty@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
cmake = "0.1.40"
